// 'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer } from 'react-toastify'
import "./globals.css";
import { CartContext } from "@/context/cartContext";
import Script from "next/script";
import Footer from "../components/footer";
import { CartProvider } from "@/context/cartContext";
import Navbar from "../components/navbar";
import 'react-toastify/dist/ReactToastify.css';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <head>
        <Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="afterInteractive" />
      </head>
      <body className="min-h-full flex flex-col">
        <Navbar />
        <CartProvider>
          <div className="mt-18"> {children} </div>
          <ToastContainer
            position="top-right"
            className="z-[9999] mt-16"
            autoClose={2000}
            theme="dark"
          />
        </CartProvider >
        <Footer />

      </body>
    </html>
  );
}
